# Generated by Django 3.0.5 on 2020-04-20 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_1c', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listusers',
            name='kod_users_1c',
            field=models.CharField(default='00000000000', max_length=11),
        ),
        migrations.AlterField(
            model_name='listusers',
            name='user_web',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_users_1c', to=settings.AUTH_USER_MODEL),
        ),
    ]
