# Generated by Django 3.0.5 on 2020-04-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_1c', '0002_auto_20200420_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listusers',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
