# Generated by Django 3.2.8 on 2021-10-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_1c', '0003_auto_20200420_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=250)),
                ('ohrana', models.BooleanField()),
            ],
        ),
    ]
