# Generated by Django 3.2.9 on 2021-12-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_1c', '0005_listusers_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listusers',
            name='role_user',
        ),
        migrations.AddField(
            model_name='listusers',
            name='user_role',
            field=models.CharField(choices=[('Security', 'Охрана труда'), ('Harmonization', 'Согласование документов'), ('Harmonization-Security', 'Охрана труда и согласовнаие документов')], default='Security', max_length=50),
        ),
        migrations.DeleteModel(
            name='TypeAccess',
        ),
    ]
